# Site settings
title: RackHD
email: your-email@domain.com
url: https://rackhd.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
skills: "Hardware Management & Orchestration"
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
#contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 202331 #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 292c3b #FD6E8A
  secondary-dark: 191b28 #A2122F
  focus: c8c6c6 #bdb76b
  grad: 444654 
  title: ffffff

# Footer settings
footer:
  copyright: 2016 Dell EMC, All rights reserved.  <p><a href="http://www.emc.com/legal/emc-corporation-privacy-statement.htm">Privacy Policy</a></p> 
  #location: Location
  social:  Find Us Around
  #credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/rack_hd 
  - title: group
    url: https://groups.google.com/forum/#!forum/rackhd 
  - title: github
    url: https://github.com/RackHD 
  - title: slack
    url: https://codecommunity.slack.com/archives/rackhd 

# Postal address (add as many lines as necessary)
address:
  - line: Dell EMC, 176 South St
  - line: Hopkinton, MA 01748

# Credits content
#credits: 'find RackHD at <a>github.com/rackhd</a> '

# Build settings
markdown: kramdown
permalink: pretty
